site_name: Amba Analysis Worker Discussion
site_description: 'documentation for amba-analysis-worker-discussion'
site_author: 'Lukas Jesche'
docs_dir: docs/
repo_name: 'ambalytics/amba-analysis-worker-discussion'
repo_url: 'https://github.com/ambalytics/amba-analysis-worker-discussion'
nav:
    - Home: index.md
    - Code Reference:
      - twitter worker: twitter_worker_ref.md
      - twitter supervisor: twitter_supervisor_ref.md

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")